export const data = {
    title: "Chess Masters Championship 2025",
    fideRated: true,
    organizerName: "International Chess Federation",
    tournamentLevel: "international",
    startDate: "2025-05-10",
    endDate: "2025-05-15",
    reportingTime: "09:00 AM",
    registrationDeadline: "2025-04-25",
    registrationDeadlineTime: "11:59 PM",
    chiefArbiterName: "Michael Torres",
    tournamentDirectorName: "Sophie Chen",
    registrationFeesCurrency: "USD",
    registrationFeesAmount: 150,
    numberOfRounds: 7,
    timeControlType: "swiss",
    timeControlDuration: "90 minutes",
    timeControlIncrement: "30 seconds",
    tournamentType: "swiss",
    nationalApproval: true,
    stateApproval: true,
    districtApproval: true,
    contactPersonName: "John Smith",
    emailId: "tournament@chessorg.com",
    contactNumber: "+1-555-123-4567",
    alternateContact: "+1-555-765-4321",
    numberOfTrophiesMale: 5,
    numberOfTrophiesFemale: 5,
    totalCashPrize: 10000,
    country: "United States",
    state: "California",
    district: "San Francisco",
    city: "San Francisco",
    pincode: "94105",
    venueAddress: "Chess Grand Hall, 123 Market Street",
    nearestLandmark: "Financial District",
    brochureUrl: "https://example.com/tournament-brochure.pdf",
    locationLatitude: 37.7749,
    locationLongitude: -122.4194,
    chessboardProvided: true,
    timerProvided: true,
    parkingFacility: 3,
    hasFoodFacility: true,
    ageCategories: [
      { gender: "male", category: "Open" },
      { gender: "female", category: "Open" },
      { gender: "male", category: "U18" },
      { gender: "female", category: "U18" },
    ],
    foodOptions: [
      { type: "breakfast", available: true },
      { type: "lunch", available: true },
      { type: "dinner", available: true },
      { type: "snacks", available: true },
      { type: "beverages", available: true },
    ],
  };